CREATE DATABASE CLINIC;
USE CLINIC;
CREATE TABLE USUARIO (
	usuario_id int AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    apellido varchar(50) not null,
    email varchar(100) NOT NULL,
    DNI CHAR(8) NOT NULL,
    telefono VARCHAR(15) NOT NULL,
    direccion VARCHAR(120),
    fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    password_hash VARCHAR(255) NOT NULL,
    estado ENUM('ACTIVO','INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    avatar VARCHAR(255),
    intentos_fallidos INT DEFAULT 0,
    bloqueado_hasta DATETIME NULL;
    CONSTRAINT PK_USUARIO PRIMARY KEY (usuario_id),
    CONSTRAINT UK_USUARIO_EMAIL UNIQUE(email),
    CONSTRAINT UK_USUARIO_DNI UNIQUE (DNI)
);
    
CREATE TABLE ROL (
	rol_id INT auto_increment,
    nombre_rol ENUM('RECEPCIONISTA','CAJERO','ADMINISTRADOR', 'DOCTOR') NOT NULL,
    CONSTRAINT PK_ROL PRIMARY KEY(rol_id)
);

CREATE TABLE ROL_USUARIO (
	rol_id INT,
    usuario_id INT,
    CONSTRAINT PK_ROL_USUARIO PRIMARY KEY (rol_id,usuario_id),
    CONSTRAINT FK_ROL_USUARIO_ROL FOREIGN KEY (rol_id) REFERENCES ROL(rol_id),
    CONSTRAINT FK_ROL_USUARIO_USUARIO FOREIGN KEY(usuario_id) REFERENCES USUARIO(usuario_id)
);

CREATE TABLE DOCTOR (
	doctor_id INT,
    especialidad VARCHAR(120) NOT NULL,
    nroColegiatura INT NOT NULL,
    CONSTRAINT PK_DOCTOR PRIMARY KEY(doctor_id),
    CONSTRAINT FK_DOCTOR FOREIGN KEY(doctor_id) REFERENCES USUARIO(usuario_id),
    CONSTRAINT UK_DOCTOR_NROCOLEGIATURA UNIQUE(nroColegiatura)
);

CREATE TABLE HORARIO (
	horario_id INT AUTO_INCREMENT,
    doctor_id INT NOT NULL,
    dia_semana ENUM('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO') NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    estado ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT PK_HORARIO PRIMARY KEY(horario_id),
    CONSTRAINT FK_HORARIO_DOCTOR FOREIGN KEY(doctor_id) REFERENCES DOCTOR (doctor_id),
    CONSTRAINT UQ_HORARIO_DOCTOR_DIA_HORA UNIQUE (doctor_id, dia_semana, hora_inicio)
);

CREATE TABLE SERVICIO (
	servicio_id INT AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL, 
    duracion INT NOT NULL,
    costo DECIMAL(10,2) NOT NULL,
    buffer INT NOT NULL DEFAULT 0,
    imagen VARCHAR(255),
    CONSTRAINT PK_SERVICIO PRIMARY KEY(servicio_id),
    CONSTRAINT UK_SERVICIO_NOMBRE UNIQUE(nombre),
    CONSTRAINT CK_SERVICIO_DURACION CHECK (duracion > 0),
    CONSTRAINT CK_SERVICIO_BUFFER  CHECK (buffer >= 0)
);

CREATE TABLE SERVICIO_DOCTOR (
	doctor_id INT,
    servicio_id INT,
    estado ENUM('ACTIVO','INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT PK_SERVICIO_DOCTOR PRIMARY KEY(doctor_id, servicio_id),
    CONSTRAINT FK_SERVICIO_DOCTOR_DOCTOR FOREIGN KEY(doctor_id) REFERENCES DOCTOR(doctor_id),
    CONSTRAINT FK_SERVICIO_DOCTOR_SERVICIO FOREIGN KEY (servicio_id) REFERENCES SERVICIO(servicio_id)
);

CREATE TABLE PACIENTE (
	paciente_id INT AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL, 
    apellido VARCHAR(50) NOT NULL,
    email VARCHAR(100), 
    DNI CHAR(8) NOT NULL, 
    telefono VARCHAR(15) NOT NULL, 
    direccion VARCHAR(299), 
    sexo ENUM('FEMENINO','MASCULINO') NOT NULL, 
	estado ENUM('ACTIVO', 'INACTIVO') NOT NULL DEFAULT 'ACTIVO',
    foto VARCHAR(255),
    CONSTRAINT PK_PACIENTE PRIMARY KEY(paciente_id),
    CONSTRAINT UQ_PACIENTE_DNI UNIQUE (DNI),
    CONSTRAINT CK_PACIENTE_TELEFONO CHECK (CHAR_LENGTH(telefono)>=9)
); 

CREATE TABLE CITA (
	cita_id INT AUTO_INCREMENT,
    paciente_id INT NOT NULL, 
    doctor_id INT NOT NULL, 
    servicio_id INT NOT NULL, 
    usuario_id INT NOT NULL,
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL, 
    hora_fin TIME NOT NULL, 
    precio_aplicado DECIMAL (10,2) NOT NULL, 
    codigo_cita CHAR(10) NOT NULL, 
    estado ENUM('RESERVADA','EXPIRADA','CANCELADA','FINALIZADA')NOT NULL DEFAULT 'RESERVADA',
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CITA PRIMARY KEY (cita_id),
    CONSTRAINT FK_CITA_PACIENTE FOREIGN KEY (paciente_id) REFERENCES PACIENTE(paciente_id),
    CONSTRAINT FK_CITA_DOCTOR FOREIGN KEY(doctor_id) REFERENCES DOCTOR (doctor_id),
    CONSTRAINT FK_CITA_SERVICIO FOREIGN KEY(servicio_id) REFERENCES SERVICIO (servicio_id),
    CONSTRAINT FK_CITA_USUARIO FOREIGN KEY(usuario_id) REFERENCES USUARIO (usuario_id),
    CONSTRAINT UK_CITA_DOCTOR_FECHA_HORA UNIQUE(doctor_id, fecha, hora_inicio),
    CONSTRAINT UK_CITA_CODIGO_CITA UNIQUE (codigo_cita)
);


CREATE TABLE PAGO (
	pago_id INT AUTO_INCREMENT,
    cita_id INT NOT NULL,
    usuario_id INT NOT NULL, 
    fecha_pago DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    monto_total DECIMAL(10,2) NOT NULL,
    metodo_pago ENUM('YAPE','EFECTIVO','TARJETA', 'PLIN') NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY (pago_id),
    CONSTRAINT FK_PAGO_CITA FOREIGN KEY (cita_id) REFERENCES CITA(cita_id),
    CONSTRAINT FK_PAGO_USUARIO FOREIGN KEY (usuario_id) REFERENCES USUARIO(usuario_id),
    CONSTRAINT UK_PAGO_CITA UNIQUE (cita_id)
);

CREATE TABLE COMPROBANTE (
	comprobante_id INT AUTO_INCREMENT,
    pago_id INT NOT NULL, 
    tipo_comprobante ENUM('BOLETA','FACTURA') NOT NULL,
    serie VARCHAR(10) NOT NULL,
    numero INT NOT NULL,
    fecha_emision DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado ENUM('EMITIDO','ANULADO') NOT NULL DEFAULT 'EMITIDO',
    monto_final DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_COMPROBANTE PRIMARY KEY(comprobante_id),
    CONSTRAINT FK_COMPROBANTE_PAGO FOREIGN KEY (pago_id) REFERENCES PAGO(pago_id),
    CONSTRAINT  UK_COMPROBANTE_SERIE_NUMERO UNIQUE (serie, numero)
);